apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "grpc"
  description: "dsjinfds"
  annotations:
    github.com/project-slug: "skalingclouds/backstagegrpc"
    backstage.io/techdocs-ref: github:https://github.com/skalingclouds/backstagegrpc
spec:
  type: service
  lifecycle: experimental
  owner: "chris"
